spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: test
    password: test
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Actuator management - some endpoints were enabled for learning purpose
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers
  endpoint:
    health:
      show-details: always
  info:
      env:
        enabled: true
server:
  shutdown: graceful
info:
  app:
    name: My e-commerce project
    description: Just a simple app
    version: 1.0.0

