spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecomdb}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${DDL_AUTO}

#Actuator management - some endpoints were enabled for learning purpose
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS}
  info:
      env:
        enabled: true
server:
  shutdown: graceful
info:
  app:
    name: My e-commerce project
    description: Just a simple app
    version: 1.0.0

